# Generated by Django 3.2.6 on 2021-10-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1),
        ),
    ]
