# Generated by Django 3.2.6 on 2021-10-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_avg_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avg_rate',
            new_name='avarage_rate',
        ),
    ]
