# Generated by Django 3.2.6 on 2021-10-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2),
        ),
    ]
